import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

interface SourceScriptureEntry {
  book: string;
  chapter: number;
  verse: number;
  text: string;
}

interface GeneratedScriptureEntry {
  reference: string;
  text: string;
}

interface BookOfMormonScriptureManifest {
  total: number;
  checksum: string;
  firstReference: string | null;
  lastReference: string | null;
  longestTextLength: number;
  shortestTextLength: number;
  over96Chars: number;
  over240Chars: number;
  over480Chars: number;
}

const BOOK_ORDER = [
  "1 Nephi",
  "2 Nephi",
  "Jacob",
  "Enos",
  "Jarom",
  "Omni",
  "Words of Mormon",
  "Mosiah",
  "Alma",
  "Helaman",
  "3 Nephi",
  "4 Nephi",
  "Mormon",
  "Ether",
  "Moroni",
] as const;

function normalizeWhitespace(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function stableHash(input: string, seed = 2089): string {
  let hash = seed;

  for (let i = 0; i < input.length; i++) {
    hash = ((hash << 5) - hash + input.charCodeAt(i)) | 0;
  }

  return Math.abs(hash).toString(16).padStart(8, "0");
}

function getBookOrder(book: string): number {
  const index = BOOK_ORDER.indexOf(book as (typeof BOOK_ORDER)[number]);

  if (index === -1) {
    throw new Error(`Unknown Book of Mormon book: ${book}`);
  }

  return index;
}

function buildReference(entry: SourceScriptureEntry): string {
  return `${entry.book} ${entry.chapter}:${entry.verse}`;
}

function compareEntries(
  a: SourceScriptureEntry,
  b: SourceScriptureEntry,
): number {
  return (
    getBookOrder(a.book) - getBookOrder(b.book) ||
    a.chapter - b.chapter ||
    a.verse - b.verse
  );
}

function validateSource(entries: SourceScriptureEntry[]): void {
  const seen = new Set<string>();

  entries.forEach((entry, index) => {
    getBookOrder(entry.book);

    if (!Number.isInteger(entry.chapter) || entry.chapter <= 0) {
      throw new Error(`Invalid chapter at index ${index}: ${entry.chapter}`);
    }

    if (!Number.isInteger(entry.verse) || entry.verse <= 0) {
      throw new Error(`Invalid verse at index ${index}: ${entry.verse}`);
    }

    const reference = buildReference(entry);
    const text = normalizeWhitespace(entry.text);

    if (!text) {
      throw new Error(`Empty scripture text at index ${index}: ${reference}`);
    }

    if (seen.has(reference)) {
      throw new Error(`Duplicate scripture reference: ${reference}`);
    }

    seen.add(reference);
  });
}

function toGeneratedEntries(
  entries: SourceScriptureEntry[],
): GeneratedScriptureEntry[] {
  return [...entries].sort(compareEntries).map((entry) => ({
    reference: buildReference(entry),
    text: normalizeWhitespace(entry.text),
  }));
}

function buildManifest(
  entries: GeneratedScriptureEntry[],
): BookOfMormonScriptureManifest {
  const lengths = entries.map((entry) => entry.text.length);
  const normalizedForHash = entries.map((entry) => [
    entry.reference,
    entry.text,
  ]);

  return {
    total: entries.length,
    checksum: stableHash(JSON.stringify(normalizedForHash)),
    firstReference: entries[0]?.reference ?? null,
    lastReference: entries.at(-1)?.reference ?? null,
    longestTextLength: lengths.length === 0 ? 0 : Math.max(...lengths),
    shortestTextLength: lengths.length === 0 ? 0 : Math.min(...lengths),
    over96Chars: lengths.filter((length) => length > 96).length,
    over240Chars: lengths.filter((length) => length > 240).length,
    over480Chars: lengths.filter((length) => length > 480).length,
  };
}

function emitScriptureModule(entries: GeneratedScriptureEntry[]): string {
  const body = entries
    .map(
      (entry) => `  {
    reference: ${JSON.stringify(entry.reference)},
    text: ${JSON.stringify(entry.text)},
  },`,
    )
    .join("\n");

  return `export interface BookOfMormonScripture {
  reference: string;
  text: string;
}

// Generated by scripts/generate-book-of-mormon-scriptures.ts.
// Do not edit by hand.
export const BOOK_OF_MORMON_SCRIPTURES: BookOfMormonScripture[] = [
${body}
];
`;
}

function emitManifestModule(manifest: BookOfMormonScriptureManifest): string {
  return `export interface BookOfMormonScriptureManifest {
  total: number;
  checksum: string;
  firstReference: string | null;
  lastReference: string | null;
  longestTextLength: number;
  shortestTextLength: number;
  over96Chars: number;
  over240Chars: number;
  over480Chars: number;
}

// Generated by scripts/generate-book-of-mormon-scriptures.ts.
// Do not edit by hand.
export const BOOK_OF_MORMON_SCRIPTURE_MANIFEST: BookOfMormonScriptureManifest =
  {
    total: ${manifest.total},
    checksum: ${JSON.stringify(manifest.checksum)},
    firstReference: ${JSON.stringify(manifest.firstReference)},
    lastReference: ${JSON.stringify(manifest.lastReference)},
    longestTextLength: ${manifest.longestTextLength},
    shortestTextLength: ${manifest.shortestTextLength},
    over96Chars: ${manifest.over96Chars},
    over240Chars: ${manifest.over240Chars},
    over480Chars: ${manifest.over480Chars},
  };
`;
}

async function main(): Promise<void> {
  const root = process.cwd();
  const sourcePath = path.join(
    root,
    "src/data/book-of-mormon-scriptures.source.json",
  );
  const outputPath = path.join(root, "src/data/book-of-mormon-scriptures.ts");
  const manifestPath = path.join(
    root,
    "src/data/book-of-mormon-scriptures.manifest.ts",
  );

  const source = JSON.parse(
    await readFile(sourcePath, "utf8"),
  ) as SourceScriptureEntry[];

  validateSource(source);

  const entries = toGeneratedEntries(source);
  const manifest = buildManifest(entries);

  await writeFile(outputPath, emitScriptureModule(entries), "utf8");
  await writeFile(manifestPath, emitManifestModule(manifest), "utf8");

  console.log(
    JSON.stringify({
      event: "book_of_mormon_scriptures_generated",
      outputPath: "src/data/book-of-mormon-scriptures.ts",
      manifestPath: "src/data/book-of-mormon-scriptures.manifest.ts",
      ...manifest,
    }),
  );
}

main().catch((error) => {
  console.error(
    JSON.stringify({
      event: "book_of_mormon_scriptures_generation_failed",
      message: error instanceof Error ? error.message : String(error),
    }),
  );
  process.exit(1);
});
