export interface BookOfMormonScriptureManifest {
  total: number;
  checksum: string;
  firstReference: string | null;
  lastReference: string | null;
  longestTextLength: number;
  shortestTextLength: number;
  over96Chars: number;
  over240Chars: number;
  over480Chars: number;
}

// Generated by scripts/generate-book-of-mormon-scriptures.ts.
// Do not edit by hand.
export const BOOK_OF_MORMON_SCRIPTURE_MANIFEST: BookOfMormonScriptureManifest =
  {
    total: 6604,
    checksum: "45282169",
    firstReference: "1 Nephi 1:1",
    lastReference: "Moroni 10:34",
    longestTextLength: 735,
    shortestTextLength: 17,
    over96Chars: 5991,
    over240Chars: 2294,
    over480Chars: 83,
  };
